---
functional:
  - Пользователь должен иметь возможность фильтровать товары и пользоваться постаничным выводом
  - Пользователь должен иметь возможность просматривать страницу товара
  - Пользователь должен иметь возможность видеть название товара, рейтинг, цену со скидкой и без
  - Пользователь должен иметь возможность добавлять товары в корзину, просматривать содержимое корзины и удалять товары из корзины
  - Пользователь должен иметь возможность после добавления товаров в корзину продолжить выбор товаров, оформление заказа и перехода на страницу оплаты
  - Корзина должна храниться в сессии браузера
non-functional:
  - Сайт должен корректно работать мобильных устройствах
  - Приложение должно быть SPA и не перезагружать страницу при действиях пользователя.
 
