---
functional:
  - Пользователь должен иметь возможность фильтровать товары и пользоваться постаничным выводом
  - Пользователь должен иметь возможность просматривать страницу товара
  - Пользователь должен иметь возможность видеть название товара, рейтинг, цену со скидкой и без
  - Пользователь должен иметь возможность добавлять товары в корзину, просматривать содержимое корзины и удалять товары из корзины
  - Пользователь должен иметь возможность после добавления товаров в корзину продолжить выбор товаров, оформление заказа и перехода на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт должен корректно работать мобильных устройствах
  - Приложение должно быть SPA и не перезагружать страницу при действиях пользователя.
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
 impcicit:
  - На сайте магазина должна быть форма сортировки по нескольким параметрам
  - Описание к товарам из каталога должно чётко и корректно отображать информацию о цене со скидкой и без скидки
